import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { StudentProvider } from "./contexts/StudentContext";
import { UserProvider } from "./contexts/UserContext";
import { TeacherProvider } from "./contexts/TeacherContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "500",
});

export const metadata: Metadata = {
  title: "Academic Haven",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <UserProvider>
          <StudentProvider>
            <TeacherProvider>{children}</TeacherProvider>
          </StudentProvider>
        </UserProvider>
      </body>
    </html>
  );
}
