import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { StudentProvider } from "./contexts/StudentContext";
import { UserProvider } from "./contexts/UserContext";
import { TeacherProvider } from "./contexts/TeacherContext";
import { AdminProvider } from "./contexts/AdminContext";
import { EventProvider } from "./contexts/EventsContext";
import { Toast } from "primereact/toast";
import "primereact/resources/themes/saga-blue/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import { Toaster } from "@/components/ui/toaster";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "500",
});

export const metadata: Metadata = {
  title: "Academic Haven",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <UserProvider>
          <AdminProvider>
            <StudentProvider>
              <TeacherProvider>
                <EventProvider>
                  {children} <Toaster />
                </EventProvider>
              </TeacherProvider>
            </StudentProvider>
          </AdminProvider>
        </UserProvider>
      </body>
    </html>
  );
}
